### PR TITLE
Fixes error in json-parser

### LINKED ISSUE #51: Auth service does not finish request
This is oberservable in the dev setup: Log yourself in and go to the start page. Refresh. Wait for >10 Minutes (It must have something todo with letting the ticket expire, so the auth service must refresh it.). Reload again. The client tries to fets `mediafile/3` as the logo:

- A request to `/system/media/get/3` (mediaservice) is issued.
- The mediaservice sends `[{'presenter': 'check_mediafile_id', 'data': {'mediafile_id': 3}}]` to `http://backend:9003/system/presenter`
- The backend sends a request to the auth service (The authentication header is missing in the logs, only the cookie is printed. Maybe @GabrielInTheWorld can adjust the logging in the auth adapter)
- I've got a huge traceback originating with `OSError: [Errno 107] Transport endpoint is not connected`
```
Traceback (most recent call last):
backend_1           |   File "/app/openslides_backend/services/auth/adapter.py", line 35, in authenticate
backend_1           |     return self.auth_handler.authenticate(headers, cookies)
backend_1           |   File "/usr/local/lib/python3.8/site-packages/authlib/auth_handler.py", line 28, in authenticate
backend_1           |     return self.validator.verify(headers, cookies)
backend_1           |   File "/usr/local/lib/python3.8/site-packages/authlib/validator.py", line 30, in verify
backend_1           |     token_encoded, cookie_encoded = self.__extractTokenAndCookie(
backend_1           |   File "/usr/local/lib/python3.8/site-packages/authlib/validator.py", line 47, in __extractTokenAndCookie
backend_1           |     raise AuthenticateException("Wrong format of headers")
backend_1           | authlib.exceptions.AuthenticateException: Wrong format of headers
backend_1           | 
backend_1           | During handling of the above exception, another exception occurred:
backend_1           | 
backend_1           | Traceback (most recent call last):
backend_1           |   File "/usr/local/lib/python3.8/site-packages/gunicorn/workers/sync.py", line 134, in handle
backend_1           |     self.handle_request(listener, req, client, addr)
backend_1           |   File "/usr/local/lib/python3.8/site-packages/gunicorn/workers/sync.py", line 175, in handle_request
backend_1           |     respiter = self.wsgi(environ, resp.start_response)
backend_1           |   File "/app/openslides_backend/http/application.py", line 128, in __call__
backend_1           |     return self.wsgi_application(environ, start_response)
backend_1           |   File "/app/openslides_backend/http/application.py", line 118, in wsgi_application
backend_1           |     response = self.dispatch_request(request)
backend_1           |   File "/app/openslides_backend/http/application.py", line 49, in dispatch_request
backend_1           |     return self.default_route(request)
backend_1           |   File "/app/openslides_backend/http/application.py", line 74, in default_route
backend_1           |     response_body, access_token = view_instance.dispatch(
backend_1           |   File "/app/openslides_backend/http/views.py", line 97, in dispatch
backend_1           |     user_id, access_token = self.get_user_id_from_headers(headers, cookies)
backend_1           |   File "/app/openslides_backend/http/views.py", line 32, in get_user_id_from_headers
backend_1           |     user_id, access_token = self.services.authentication().authenticate(
backend_1           |   File "/app/openslides_backend/services/auth/adapter.py", line 37, in authenticate
backend_1           |     self.logger.debug(f"Error in auth service: {e.message}")
backend_1           | AttributeError: 'AuthenticateException' object has no attribute 'message'
backend_1           | [2020-11-17 08:22:59 +0000] [132] [ERROR] Socket error processing request.
backend_1           | Traceback (most recent call last):
backend_1           |   File "/usr/local/lib/python3.8/site-packages/gunicorn/workers/sync.py", line 133, in handle
backend_1           |     req = next(parser)
backend_1           |   File "/usr/local/lib/python3.8/site-packages/gunicorn/http/parser.py", line 41, in __next__
backend_1           |     self.mesg = self.mesg_class(self.cfg, self.unreader, self.req_count)
backend_1           |   File "/usr/local/lib/python3.8/site-packages/gunicorn/http/message.py", line 186, in __init__
backend_1           |     super().__init__(cfg, unreader)
backend_1           |   File "/usr/local/lib/python3.8/site-packages/gunicorn/http/message.py", line 53, in __init__
backend_1           |     unused = self.parse(self.unreader)
backend_1           |   File "/usr/local/lib/python3.8/site-packages/gunicorn/http/message.py", line 235, in parse
backend_1           |     self.headers = self.parse_headers(data[:idx])
backend_1           |   File "/usr/local/lib/python3.8/site-packages/gunicorn/http/message.py", line 73, in parse_headers
backend_1           |     remote_addr = self.unreader.sock.getpeername()
backend_1           | OSError: [Errno 107] Transport endpoint is not connected
```
    Note: There are also other errors, that have to be resolved, like the `AttributeError`. It seems, that it is not well tested in conjunction
- The only logs from the auth service is
```
auth_1              | BadRequestError: request aborted
auth_1              |     at IncomingMessage.onAborted (/app/node_modules/raw-body/index.js:231:10)
auth_1              |     at IncomingMessage.emit (events.js:315:20)
auth_1              |     at abortIncoming (_http_server.js:561:9)
auth_1              |     at socketOnClose (_http_server.js:554:3)
auth_1              |     at Socket.emit (events.js:327:22)
auth_1              |     at TCP.<anonymous> (net.js:673:12)
```

First, please add more (debug) logging to the auth service, e.g. when a request is received, which payxload, which url. Also a debug statement about the result of the request. Currently I can only trace it to the request the backend sends, after this is only silence and guessing from my side.

Finally, the backend gets killed and restarted by gunicorn because the worker timed out:
```
backend_1           | [2020-11-17 08:22:58 +0000] [7] [CRITICAL] WORKER TIMEOUT (pid:130)
backend_1           | [2020-11-17 08:22:58 +0000] [130] [INFO] Worker exiting (pid: 130)
```
This message is acutally before the logs of the auth service, so it is clear why the auth logs a `request abroted` when the backend is killed. But the timeout is >10 seconds - this is too long to respond from the auth server.

Something is wrong with the communication between both.

If I log off and log in again, the fetching of the mediafile works for some time again. -> I strongly suspect the refreshing mechanism to hang in the auth service.

### PR DESCRIPTION
**Pull request by GabrielInTheWorld**
Fixes #51

### CODE REVIEW

File: auth/src/express/middleware/parser.ts [hunk 1]
```diff
@@ -0,0 +1,25 @@
+import { NextFunction, Request, Response } from 'express';
+
+import { Logger } from '../../api/services/logger';
+
+export namespace Parser {
```
Comment (FinnStutzenstein) [inline auth/src/express/middleware/parser.ts:5]: Since this is a middleware, you either just write a middleware (and not name it `Parser`) or separate is clearly: First, you have a parser,but the parser must not know about a request, response, ... Second, you have the middleware, which just does something like this:
```
try {
    req.body = parser.ensureValidJson(req.body);
} catch (e) {
    //return a 400er -> The req.body was not valid. What is "valid" is defined by the parser
}
```

File: auth/src/express/middleware/parser.ts [hunk 2]
```diff
@@ -0,0 +1,25 @@
...
+    export function parseJson(req: Request, res: Response, next: NextFunction): void {
+        const body = req.body;
+        Logger.debug('Trying to parse the request.body: ', body);
+        if (!body || !isValidJsonFormat(body)) {
+            req.body = {};
+        } else {
+            try {
+                req.body = JSON.parse(body);
+            } catch (e) {
+                Logger.error('Cannot read request.body: ', e);
```
Comment (FinnStutzenstein) [inline auth/src/express/middleware/parser.ts:19]: At this point you should return a 400er. Why: In `isValidJsonFormat` you checked that it is a string and it is (if it is valid json) an object or array. If this is true and the decoding fails, this is an invalid user input which should not be silenty ignored.

File: auth/src/express/middleware/parser.ts [hunk 3]
```diff
@@ -0,0 +1,25 @@
+import { NextFunction, Request, Response } from 'express';
+
+import { Logger } from '../../api/services/logger';
+
+export namespace Parser {
+    function isValidJsonFormat(input: any): boolean {
+        return typeof input === 'string' && (input.trim().startsWith('{') || input.trim().startsWith('['));
```
Comment (FinnStutzenstein) [inline auth/src/express/middleware/parser.ts:7]: I would propose to accept `null`, `undefined`, `""` and a string srtating with `{`. The three first cases should be converted (can also be done by the parser, see another comment) to `{}`, and the forth one can be parsed. If there was an error, a `ParserError` is thrown.

File: auth/libraries/pip-auth/authlib/validator.py [hunk 4]
```diff
@@ -99,7 +102,7 @@ def __verify_ticket_from_auth_service(
         """
         self.debug_fn("Validator.__verify_ticket_from_auth_service")
         response = self.http_handler.send_internal_request(
-            "/api/authenticate", headers=headers, cookies=cookies
+            "/api/authenticate", headers=headers, cookies=cookies, payload={}
```
Comment (FinnStutzenstein) [inline auth/libraries/pip-auth/authlib/validator.py:105]: This should not be needed, if the parser accepts an empty payload (`null`, `undefined` `""`) and interpret it as `{}`.

File: auth/src/express/middleware/parser.ts (hunk 3 above)
Comment (FinnStutzenstein) [reply auth/src/express/middleware/parser.ts:7]: Also I would expect the middleware to be a clean invariant: Iff the request payload is ok, it is always a parsed object. If not, the middleware will provide a valid 400er response. With this invariant (object or nothing) the behaviour is very clear. I think there is no need to accept arrays, too.

**Review by FinnStutzenstein — CHANGES_REQUESTED** [review]

**Review by FinnStutzenstein — APPROVED** [review]
Looks good. I do have some remark for the tests:
- Check for every request, that the response is json (I noticed that `sendRequestAndValidateForbiddenRequest` only validates the status code, but not the actual payload)
- use the has method to generate a hash in the is-equals test
- login tests with wrong username/password are missing
- General a bit more checking about the results (e.g. that it is really the anonymous users in the second whoami testcase, or the content of `sessions.sessions` in list sessions testcase)

**Comment by GabrielInTheWorld** [comment]
Thanks for your reply. I will improve the tests.

**Comment by FinnStutzenstein** [comment]
> I will improve the tests.

You did not do it here, right? If not, please create an issue, so we can keep track of it.
