### PR TITLE
Fixes hot-reloading of service

### LINKED ISSUE #15: Requests from Backend are blocked
How to replicate:

- checkout openslides4-dev
- `cd openslides-client && git checkout master && git pull upstream master` (assuming `upstream` is set correctly)
- `cd ../openslides-backend && git checkout master && git pull upstream master` (s.a.)
- go to `http://localhost:8000/topics/new` and try to create a topic

Output:

    backend_1               | DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): auth:9004
    auth_1                  | [22.07.2020 -- 07:16:54]: [ 'POST -- /' ]
    auth_1                  | [22.07.2020 -- 07:16:54]: [ ' -- blocked.' ]
    backend_1               | DEBUG:urllib3.connectionpool:http://auth:9004 "POST / HTTP/1.1" 200 54
    backend_1               | DEBUG:openslides_backend.services.authentication:Get repsonse: {'success': False, 'message': 'Domain has been blocked!'}

### LINKED ISSUE #17: NEED HELP: server is not restarting after file-changes in development environment
- With nodemon: The service is restarting after file-changes, but changes are not applied.
- With ts-node-dev: The service is not restarting.

### PR DESCRIPTION
**Pull request by GabrielInTheWorld**
- Server will reload when changes made (and changes are applied).
- CORS is disabled.
- No datastore-writer anymore, because it is not used.

Fixes #17
Fixes #15

### CODE REVIEW

File: auth/src/config/index.ts [hunk 1]
```diff
@@ -2,8 +2,14 @@ import fs from 'fs';
 
 export namespace Config {
     export const DATABASE_PATH = 'database/';
-    export const DATASTORE_READER = `${process.env.INSTANCE_DOMAIN || `http://reader`}:9010`;
-    export const DATASTORE_WRITER = `${process.env.INSTANCE_DOMAIN || 'http://writer'}:9011`;
+    export const DATASTORE_READER = `http://${process.env.DATASTORE_READER_HOST || 'reader'}:${parseInt(
+        process.env.DATASTORE_READER_PORT || '',
```
Comment (FinnStutzenstein) [inline auth/src/config/index.ts:6]: If you haven't concrete defaults, throw an error and termintate the server with a non-zero exit code.
